changed the folder structure and optimized the code
marees7/rishi-aug-2024 pull request #1
Opened 2024-12-02 15:25 UTC by rsi27c

Changed the folder structure ,Handled the errors properly and modified some api

2024-12-09 11:43 UTC, marees7 commented on api/handlers/admin.go
> +		offset = 0
set default value on cconstant file if not present use constant / default

2024-12-09 11:46 UTC, marees7 commented on api/handlers/admin.go
> +func (handler *AdminHandler) GetSingleUser(ctx echo.Context) error {
Use proper function names if you get all users the function name should be GetUsers if it is single user it should be GetUser

2024-12-09 11:52 UTC, marees7 commented on api/handlers/auth.go
>  		loggers.WarningLog.Println(err)
If it is warning you can use log.warn which makes read easier

2024-12-12 13:30 UTC, haritha-siv requested changes

2024-12-12 13:30 UTC, haritha-siv commented on cmd/main.go
* use struct to pass DB
* main should contain only the router initialization, dbconnection initialization and automigration
* why both Connect(), GetDB() are used

2024-12-12 13:30 UTC, haritha-siv commented on internals/connection.go
* Return db using the connect() and use struct instead of using public variable

2024-12-12 13:30 UTC, haritha-siv commented on constants/constants.go
* use minimal default limit,10 or 20

2024-12-12 13:30 UTC, haritha-siv commented on common/helpers/helpers.go
>  type UserView struct {
Why have you added omit empty tags for all the fields in the UserView struct?

2024-12-12 13:30 UTC, haritha-siv commented on api/handlers/admin.go
> +	param := ctx.QueryParam("limit")
why are you overwriting the variable param?

2024-12-12 13:30 UTC, haritha-siv commented on api/handlers/admin.go
> +	status, err := handler.AdminServices.GetUsers(&users, role, limit, offset)
* To retrieve users why are you passing empty users list?
* Set status codes based on the errors your getting in the handler, don't pass from the service

2024-12-12 13:30 UTC, haritha-siv commented on api/handlers/admin.go
> +	//call the get User By ID service
* Don't pass empty user to retrieve user
* Set status codes based on the errors your getting in the handler, don't pass from the service

2024-12-12 13:30 UTC, haritha-siv commented on api/handlers/admin.go
> +	if status, err := handler.AdminServices.UpdateCategory(&category, categoryid, role); err != nil {
* Don't pass empty category to the service
* Set status codes based on the errors your getting in the handler, don't pass from the service

2024-12-12 13:30 UTC, haritha-siv commented on api/handlers/admin.go
> +		Data: map[string]interface{}{
* Return the deleted data id, instead of deleted_at time

2024-12-12 13:30 UTC, haritha-siv commented on api/handlers/admin.go
> +	status, err := handler.AdminServices.CreateCategory(&category, role)
- Set status codes based on the errors your getting in the handler, don't pass from the service

2024-12-12 13:30 UTC, haritha-siv commented on common/helpers/helpers.go
* helpers package conatains the commonly used functions and not structs
* use dto or models package to keep struct data

2024-12-12 13:30 UTC, haritha-siv commented on api/handlers/user.go
> +func (handler *UserHandler) GetUsers(ctx echo.Context) error {
Use proper method name, based on its functionality

2024-12-12 13:30 UTC, haritha-siv commented on api/handlers/user.go
> +	status, err := handler.UserServices.GetUsers(&users, limit, offset)
* Don't pass empty users to the service
* Set status codes based on the errors your getting in the handler, don't pass from the service

2024-12-12 13:30 UTC, haritha-siv commented on api/handlers/user.go
> +// retrieve every users public fields
What is the purpose of this method?

2024-12-12 13:30 UTC, haritha-siv commented on api/handlers/user.go
> +func (handler *UserHandler) GetUser(ctx echo.Context) error {
* What is the purpose of this method?

2024-12-12 13:30 UTC, haritha-siv commented on api/handlers/user.go
> +// retrieve single user public fields using username
* Don't pass empty user to the service
* Set status codes based on the errors your getting in the handler, don't pass from the service

2024-12-12 13:30 UTC, haritha-siv commented on api/handlers/user.go
> +	//call the create post service
* why have you not validated the Createpost data?

2024-12-12 13:30 UTC, haritha-siv commented on api/handlers/user.go
> +	if status, err := handler.UserServices.CreatePost(&post, userid); err != nil {
* Set status codes based on the errors your getting in the handler, don't pass from the service

2024-12-12 13:30 UTC, haritha-siv commented on api/handlers/user.go
> +	//call the update post service
* Set status codes based on the errors your getting in the handler, don't pass from the service

2024-12-12 13:30 UTC, haritha-siv commented on api/handlers/user.go
> +func (handler *UserHandler) GetPosts(ctx echo.Context) error {
* Use proper method names, in handler u have used GetPosts, in service GetPost
* Y have u used postID as a parameter to GetPosts
* Don't pass empty Post struct to the service
* Set status codes based on the errors your getting in the handler, don't pass from the service
* Add search param to search based on title

2024-12-12 13:30 UTC, haritha-siv commented on api/handlers/user.go
> +	if status, err := handler.UserServices.CreateComment(&comment, userid, postid); err != nil {
* Set status codes based on the errors your getting in the handler, don't pass from the service

2024-12-12 13:30 UTC, haritha-siv commented on pkg/models/models.go
> +package models
* Use UUID for primarykey instead of int
* Y have u used plural terms?

2024-12-12 13:30 UTC, haritha-siv commented on api/handlers/user.go
> +	if status, err := handler.UserServices.UpdateComment(&comment, userid, commentid, role); err != nil {
* Set status codes based on the errors your getting in the handler, don't pass from the service

2024-12-12 13:33 UTC, haritha-siv commented on api/handlers/user.go
> +	return ctx.JSON(http.StatusOK, helpers.ResponseJson{
Give postID also in response

2024-12-12 13:34 UTC, haritha-siv commented on api/handlers/user.go
> +	if status, err := handler.UserServices.DeleteComment(&comment, userid, commentid, role); err != nil {
* Set status codes based on the errors your getting in the handler, don't pass from the service

2024-12-12 13:35 UTC, haritha-siv commented on api/handlers/user.go
> +// retrieve every categories available
* Don't pass empty category struct to the service
* Set status codes based on the errors your getting in the handler, don't pass from the service

2024-12-12 13:36 UTC, haritha-siv commented on api/handlers/user.go
> +func (handler *UserHandler) UpdateComment(ctx echo.Context) error {
* Set status codes based on the errors your getting in the handler, don't pass from the service
* add validation for comment data

2024-12-12 14:15 UTC, haritha-siv requested changes

2024-12-12 14:15 UTC, haritha-siv commented on api/handlers/user.go
> +	if err := ctx.Bind(&post); err != nil {
* Add validation for post data to be updated

2024-12-12 14:15 UTC, haritha-siv commented on api/handlers/user.go
> +func (handler *UserHandler) GetComments(ctx echo.Context) error {
* Use proper method names, in handler u have used GetComments, in service GetComment
* Add search params to search comments based on content

2024-12-12 14:15 UTC, haritha-siv commented on api/handlers/user.go
> +	status, err := handler.UserServices.GetComment(&comments, postid)
* Don't pass empty comment struct to the service
* Set status codes based on the errors your getting in the handler, don't pass from the service

2024-12-12 14:15 UTC, haritha-siv commented on api/handlers/user.go
> +	for _, comment := range comments {
* Y are you returning only particular fields in response, either return their UUID or enitre data

2024-12-12 14:15 UTC, haritha-siv commented on api/handlers/user.go
> +package handlers
* add seperate files for each modules:comments, post, instead of dumping all in the same file user.go

2024-12-12 14:15 UTC, haritha-siv commented on api/middlewares/requireauth.go
> +			return c.JSON(http.StatusGatewayTimeout, helpers.ResponseJson{
Y have u used status code as badgateway?

2024-12-12 14:15 UTC, haritha-siv commented on api/middlewares/requireauth.go
>  			return c.JSON(http.StatusNotFound, helpers.ResponseJson{
y have u used status code as StatusNotFound

2024-12-12 14:15 UTC, haritha-siv commented on api/middlewares/requireauth.go
>  			return c.JSON(http.StatusBadRequest, helpers.ResponseJson{
* y have u used status code as StatusBadRequest?

2024-12-12 14:15 UTC, haritha-siv commented on api/middlewares/requireauth.go
>  			return c.JSON(http.StatusBadRequest, helpers.ResponseJson{
* y have u used status code as StatusBadRequest

2024-12-12 14:15 UTC, haritha-siv commented on constants/constants.go
> +package constants
* constants file can be placed inside helpers or common folder

2024-12-12 14:15 UTC, haritha-siv commented on api/handlers/auth.go
> +	tokenstr, err := validation.GenerateToken(user)
y have u used status code as internalserver error?

2024-12-12 14:15 UTC, haritha-siv commented on api/handlers/auth.go
> +	user, err := handler.AuthServices.Login(&login)
y have u used status code as internalserver error

2024-12-12 14:15 UTC, haritha-siv commented on api/handlers/auth.go
> +	if login.Password == "" {
* y have u used status code as internalserver error

2024-12-12 14:15 UTC, haritha-siv commented on api/handlers/auth.go
> +		return ctx.JSON(http.StatusInternalServerError, helpers.ResponseJson{
y have u used status code as internalserver error

2024-12-12 14:15 UTC, haritha-siv commented on api/handlers/auth.go
> +func (handler *AuthHandler) Signup(ctx echo.Context) error {
* Set status codes based on the errors your getting in the handler, don't pass from the service

2024-12-12 14:15 UTC, haritha-siv commented on api/services/admin.go
> +	if role == "admin" {
* This validation can be done in the handler itsellf ryt?
* Change this validation of role in the handler itself

2024-12-12 14:15 UTC, haritha-siv commented on api/services/services.go
> +package services
* What is the use of this?
* Why dont u add this in each service file?

2024-12-12 14:15 UTC, haritha-siv commented on api/services/services.go
> +func GetAuthService(repository *repositories.Repository) *Services {
* Why have u used the function name as "GetAuthService"?, Why the term Get is used here?

2024-12-12 14:15 UTC, haritha-siv commented on api/services/user.go
> +package services
* Don't pass empty struct data to the service
* Dont pass status codes from service, provide those in handlers based on the errors
* make this change for all the upcoming methods

2024-12-12 14:15 UTC, haritha-siv commented on api/services/admin.go
> +package services
* Don't pass empty struct data to the services in GET and DELETE method
* Dont pass status codes from service, provide those in handlers based on the errors
* make this change for all the upcoming methods

2024-12-12 14:15 UTC, haritha-siv commented on api/services/user.go
> +func (repo userService) GetUsers(users *[]models.Users, limit, offset int) (int, error) {
* What is the purpose of this method?

2024-12-12 14:15 UTC, haritha-siv commented on api/services/user.go
> +func (repo userService) GetUser(users *models.Users, username string) (int, error) {
* What is the purpose of this method?

2024-12-12 14:15 UTC, haritha-siv commented on api/services/user.go
> +func (repo userService) GetPost(posts *[]models.Posts, startdate string, enddate string, postid int) (int, error) {
* Use proper method name based on their functionality

2024-12-12 14:15 UTC, haritha-siv commented on api/services/user.go
> +	if startdate == "" && enddate != "" {
* Validation should be done in the handler

2024-12-12 14:15 UTC, haritha-siv commented on api/services/user.go
> +func (repo userService) GetComment(comments *[]models.Comments, postid int) (int, error) {
* Use proper method name based on the functionality

2024-12-12 14:15 UTC, haritha-siv commented on api/validation/validation.go
>  package validation
* Add validation for updating and creating the data to check if all the required field are given

2024-12-12 14:15 UTC, haritha-siv commented on pkg/loggers/loggers.go
> +package loggers
* log file should be generated inside the loggers

2024-12-12 14:19 UTC, haritha-siv commented on api/repositories/repositories.go
>  )
* Y have u used seperate file for this, u can add in each repo ryt?
* use proper naming

2024-12-12 14:20 UTC, haritha-siv commented on api/repositories/auth.go
>  	data := db.Where("email=?", details.Email).First(&user)
* Why are you checking user.ID == 0
* dont hardcode, use error data to check if the user is found or not

2024-12-12 14:23 UTC, haritha-siv commented on api/repositories/user.go
> +package repositories
* Dont return status codes, check for the error data and set proper status codes in the handler

2024-12-17 05:42 UTC, haritha-siv commented on api/routes/auth.go
> +func AuthRoute(server *echo.Echo, db *gorm.DB) {
* leave a line before the comment line 
* Make this change in all the places

2024-12-17 08:01 UTC, haritha-siv commented on api/handlers/admin.go
> +	limit_param := ctx.QueryParam("limit")
* dont use snake case for variable names
* dont use the word param, u could name as limitStr, which means that the limit is in string format
* change it in all the places

2024-12-17 08:01 UTC, haritha-siv commented on api/handlers/admin.go
> +	getRole := (ctx.Get("role"))
* dont prefix variable names with get, create, update etc....
* u could use roleCtx instead
* make this change whereever necessary
```suggestion
	getRole := (ctx.Get("role"))
    roleCtx := (ctx.Get("role"))
```

2024-12-17 08:01 UTC, haritha-siv commented on api/handlers/auth.go
> +	return ctx.JSON(http.StatusOK, dto.ResponseJson{
* Use created status code for POST operations

2024-12-17 08:01 UTC, haritha-siv commented on api/handlers/category.go
> +package handlers
* use common function to check the role

2024-12-17 08:01 UTC, haritha-siv commented on pkg/models/models.go
> +	Category_name string         `json:"category_name,omitempty" gorm:"unique;not null;"`
* Use Pascal or Camel case for variables
```suggestion
	Category_name string         `json:"category_name,omitempty" gorm:"unique;not null;"`
	CategoryName string         `json:"category_name,omitempty" gorm:"unique;not null;"`


```

2024-12-17 08:01 UTC, haritha-siv commented on api/handlers/category.go
> +	}
* use forbidden status code to report if the user doest have permissions to access that page

2024-12-17 08:01 UTC, haritha-siv commented on api/handlers/category.go
> +			"updated_at":    category.UpdatedAt,
* either return categoryID alone or the entire category data

2024-12-17 08:01 UTC, haritha-siv commented on api/handlers/category.go
> +		return ctx.JSON(http.StatusUnauthorized, dto.ResponseJson{
* change the status code

2024-12-17 08:01 UTC, haritha-siv commented on api/handlers/comment.go
> +	if err := validation.CommentValidation(&comment); err != nil {
* change the function name to ValidateComment

2024-12-17 08:01 UTC, haritha-siv commented on api/handlers/comment.go
> +	userid, err := uuid.Parse(user_str)
* userid --> userID

2024-12-17 08:01 UTC, haritha-siv commented on api/handlers/comment.go
> +	return ctx.JSON(http.StatusOK, dto.ResponseJson{
* change status code

2024-12-17 08:01 UTC, haritha-siv commented on api/handlers/comment.go
> +	user := ctx.Get("user_id")
```suggestion
	user := ctx.Get("user_id")
	userIDCtx := ctx.Get("user_id")
```

2024-12-17 08:01 UTC, haritha-siv commented on api/handlers/comment.go
> +	content := ctx.QueryParam("find")
* use search/keyword instead of find

2024-12-17 08:01 UTC, haritha-siv commented on api/handlers/comment.go
> +func (handler *CommentHandler) GetComment(ctx echo.Context) error {
* change this method name

2024-12-17 08:01 UTC, haritha-siv commented on api/handlers/post.go
> +	if err := validation.PostsValidation(&post); err != nil {
* change the function name used here

2024-12-17 08:01 UTC, haritha-siv commented on api/handlers/post.go
> +func (handler *PostHandler) GetPosts(ctx echo.Context) error {
* optimize the searching method

2024-12-17 08:01 UTC, haritha-siv commented on api/repositories/category.go
> +		return nil, fmt.Errorf("user not found")
* change the error message

2024-12-17 08:01 UTC, haritha-siv commented on api/repositories/user.go
> +	GetUser(usernaem string) (*models.User, error)
* change the spelling for username

2024-12-17 08:01 UTC, haritha-siv commented on api/repositories/category.go
> +	}
* change the error message

2024-12-17 08:01 UTC, haritha-siv commented on api/repositories/category.go
> +
* remove this validation

2024-12-17 08:01 UTC, haritha-siv commented on api/repositories/category.go
> +	} else if checkCategory.CategoryID != categoryid {
* remove this validation

2024-12-17 08:01 UTC, haritha-siv commented on api/handlers/comment.go
> +	id := ctx.QueryParam("post_id")
* use post_id as path param

2024-12-17 08:01 UTC, haritha-siv commented on api/repositories/comment.go
> +			return nil, fmt.Errorf("user not found")
* change the error message

2024-12-17 08:01 UTC, haritha-siv commented on api/repositories/comment.go
> +		}
* remove this

2024-12-17 08:01 UTC, haritha-siv commented on api/repositories/comment.go
> +func (db *commentRepository) GetComment(postid uuid.UUID, content string) (*[]models.Comment, error) {
* add pagination filter

2024-12-17 08:01 UTC, haritha-siv commented on api/repositories/comment.go
> +func (db *commentRepository) UpdateComment(comment *models.Comment, commentid uuid.UUID, role string) error {
* updation of comment can be done only by the one who commented and not admins

2024-12-17 08:01 UTC, haritha-siv commented on api/repositories/post.go
> +func InitpostRepository(db *gorm.DB) PostRepository {
InitpostRepositiory--> InitPostRepositiory

2024-12-17 08:01 UTC, haritha-siv commented on api/repositories/post.go
> +	}
* remove this

2024-12-17 08:01 UTC, haritha-siv commented on api/repositories/post.go
> +	if post.UserID == checkPost.UserID || role == "admin" {
* dont let admins to update the post contents

2024-12-17 08:01 UTC, haritha-siv commented on api/repositories/post.go
> +func (db *postRepository) GetPosts(startdate string, enddate string, postid uuid.UUID, title string) (*[]models.Post, error) {
* change logic for startDate, endDate filters
* add paginations

2024-12-17 08:01 UTC, haritha-siv commented on api/repositories/user.go
> +func (db *userRepository) GetUsers(limit int, offset int) (*[]models.User, error) {
* Add pagination

2024-12-17 08:01 UTC, haritha-siv commented on api/services/admin.go
> +	users, err := repo.Users.GetUsers(limit, offset)
* calculate the pagination and send to repo

2024-12-17 08:01 UTC, haritha-siv commented on api/services/admin.go
> +func (repo *adminService) GetUser(username string, role string) (*models.User, error) {
* What is the use of role parameter here?

2024-12-17 08:01 UTC, haritha-siv commented on api/services/category.go
> +package services
* optimize the code

2024-12-17 08:01 UTC, haritha-siv commented on api/services/comment.go
> +package services
* optimize the code

2024-12-17 08:01 UTC, haritha-siv commented on api/services/post.go
> +package services
* optimize the code

2024-12-17 08:01 UTC, haritha-siv commented on api/validation/validation.go
> +		return fmt.Errorf("descroption cannot be empty")
* check the spelling

2024-12-17 08:01 UTC, haritha-siv commented on common/constants/constants.go
> +package constants
* add admin role also

2024-12-18 14:02 UTC, haritha-siv commented on api/handlers/admin.go
> +func (handler *AdminHandler) GetUsers(ctx echo.Context) error {
* add name field 
* add filter for name field

2024-12-18 14:02 UTC, haritha-siv commented on api/handlers/admin.go
> +		//call the get Users service
* change the function name and variable names

2024-12-18 14:02 UTC, haritha-siv commented on api/handlers/admin.go
> +func (handler *AdminHandler) GetUser(ctx echo.Context) error {
* when retrieving a single data,data not found should be shown as an error and should not retturn empty data

2024-12-18 14:02 UTC, haritha-siv commented on api/handlers/auth.go
> +	if err := handler.AuthServices.Signup(&user); err != nil {
* send custom error response if the user already exists based on (emailID)

2024-12-18 14:02 UTC, haritha-siv commented on api/handlers/comment.go
> +		},
* check spelling

2024-12-18 14:02 UTC, haritha-siv commented on api/handlers/comment.go
> +	commentid, err := uuid.Parse(id)
* use CamelCase

2024-12-18 14:02 UTC, haritha-siv commented on api/handlers/comment.go
> +	if errs != nil {
* change the variable

2024-12-18 14:02 UTC, haritha-siv commented on api/repositories/comment.go
> +func (db *commentRepository) GetComments(postID uuid.UUID, commentMap map[string]interface{}) (*[]models.Comment, *dto.ErrorResponse) {
* optimize the filter usage

2024-12-18 14:02 UTC, haritha-siv commented on api/repositories/post.go
> +	return &post, nil
* check if record is retrived if from and end date are same

2024-12-18 14:02 UTC, haritha-siv commented on api/repositories/post.go
> +func (db *postRepository) GetPosts(postID uuid.UUID, postMap map[string]interface{}) (*[]models.Post, error) {
* optimize the code

2024-12-18 14:02 UTC, haritha-siv commented on api/repositories/post.go
> +	if post.UserID == postData.UserID {
* remove this validation

2024-12-18 14:02 UTC, haritha-siv commented on api/repositories/post.go
> +		return nil, &dto.ErrorResponse{Status: http.StatusUnauthorized, Error: "cannot delete other users post"}
* change the status code as per the error

2024-12-19 11:14 UTC, haritha-siv commented on api/handlers/comment.go
> +package handlers
* do few modifications in the response message

2024-12-19 11:14 UTC, haritha-siv commented on api/repositories/category.go
> +		return &dto.ErrorResponse{Status: http.StatusNotFound, Error: data.Error.Error()}
* check the status code

2024-12-19 11:14 UTC, haritha-siv commented on api/repositories/category.go
> +	} else if data.RowsAffected == 0 {
* check the status code

2024-12-19 11:14 UTC, haritha-siv commented on api/repositories/comment.go
> +	if commentData.UserID == comment.UserID {
* remove this extra validation

2024-12-19 11:14 UTC, haritha-siv commented on api/repositories/comment.go
> +	if commentData.UserID == userID || validation.ValidateRole(role) {
* process this validation 1st before others

2024-12-19 11:14 UTC, haritha-siv commented on api/repositories/post.go
> +	} else if fromDate != "" && toDate == "" {
* check the functionality after and before removing between case

2024-12-19 11:14 UTC, haritha-siv commented on api/repositories/user.go
> +	data := db.Preload("Posts").Preload("Comments").Where("username=?", username).First(&user)
* check this

2024-12-19 11:14 UTC, haritha-siv commented on api/repositories/user.go
> +package repositories
* add Delete API and Update API
* add total count also

2024-12-23 08:00 UTC, merged